name: primitives_ffi
description: A super simple example of calling Zig code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  ffi: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

